export const styles = {
  wrapper: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#f0f4f8",
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  sidebar: {
    width: "280px",
    background: "linear-gradient(180deg, #1a1a2e 0%, #16213e 100%)",
    color: "#fff",
    display: "flex",
    flexDirection: "column",
    position: "fixed",
    height: "100vh",
    boxShadow: "4px 0 24px rgba(0, 0, 0, 0.1)",
  },
  logoSection: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    padding: "28px 24px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
  },
  logoIcon: {
    fontSize: "32px",
  },
  logoText: {
    fontSize: "22px",
    fontWeight: "700",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    letterSpacing: "-0.5px",
  },
  nav: {
    flex: 1,
    padding: "24px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  navButton: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    padding: "14px 18px",
    border: "none",
    background: "transparent",
    color: "rgba(255, 255, 255, 0.6)",
    fontSize: "15px",
    fontWeight: "500",
    borderRadius: "12px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    textAlign: "left",
    width: "100%",
    position: "relative",
  },
  navButtonActive: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "#fff",
    boxShadow: "0 4px 15px rgba(102, 126, 234, 0.4)",
  },
  navIcon: {
    fontSize: "20px",
  },
  navLabel: {
    flex: 1,
  },
  activeIndicator: {
    width: "4px",
    height: "24px",
    background: "#fff",
    borderRadius: "2px",
    position: "absolute",
    right: "8px",
  },
  sidebarFooter: {
    padding: "20px",
    borderTop: "1px solid rgba(255, 255, 255, 0.08)",
  },
  userInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "14px",
    background: "rgba(255, 255, 255, 0.05)",
    borderRadius: "12px",
  },
  avatar: {
    width: "44px",
    height: "44px",
    borderRadius: "12px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "600",
    fontSize: "18px",
  },
  userName: {
    fontWeight: "600",
    fontSize: "14px",
    color: "#fff",
  },
  userRole: {
    fontSize: "12px",
    color: "rgba(255, 255, 255, 0.5)",
    marginTop: "2px",
  },
  main: {
    flex: 1,
    marginLeft: "280px",
    minHeight: "100vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "24px 40px",
    background: "#fff",
    borderBottom: "1px solid #e5e9f2",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  pageTitle: {
    fontSize: "28px",
    fontWeight: "700",
    color: "#1a1a2e",
    margin: 0,
    letterSpacing: "-0.5px",
  },
  breadcrumb: {
    fontSize: "14px",
    color: "#8492a6",
    marginTop: "6px",
  },
  addButton: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "14px 28px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    fontSize: "15px",
    fontWeight: "600",
    cursor: "pointer",
    boxShadow: "0 4px 15px rgba(102, 126, 234, 0.35)",
    transition: "all 0.3s ease",
  },
  addIcon: {
    fontSize: "20px",
    fontWeight: "300",
  },
  content: {
    padding: "32px 40px",
  },
  dashboardGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "28px",
  },
  fullWidth: {
    width: "100%",
  },
  card: {
    background: "#fff",
    borderRadius: "20px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.05)",
    overflow: "hidden",
    border: "1px solid #e5e9f2",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "24px 28px",
    borderBottom: "1px solid #f0f4f8",
    background: "#fafbfc",
  },
  cardTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#1a1a2e",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  cardBody: {
    padding: "24px 28px",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  formRow: {
    display: "flex",
    gap: "20px",
    flexWrap: "wrap",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#4a5568",
  },
  input: {
    padding: "12px 16px",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    fontSize: "15px",
    outline: "none",
    transition: "border-color 0.2s",
  },
  textarea: {
    padding: "12px 16px",
    borderRadius: "10px",
    border: "1px solid #e2e8f0",
    fontSize: "15px",
    outline: "none",
    resize: "vertical",
    fontFamily: "inherit",
  },
  submitBtn: {
    padding: "14px 24px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    boxShadow: "0 4px 15px rgba(102, 126, 234, 0.35)",
    alignSelf: "flex-start",
    marginTop: "10px",
  },
  viewAllBtn: {
    background: "none",
    border: "none",
    color: "#667eea",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },

  // Mobile-specific styles
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 998,
  },
  sidebarMobile: {
    position: "fixed",
    left: "-280px",
    zIndex: 999,
    transition: "left 0.3s ease",
  },
  sidebarMobileOpen: {
    left: 0,
  },
  closeSidebarBtn: {
    marginLeft: "auto",
    background: "rgba(255, 255, 255, 0.1)",
    border: "none",
    color: "#fff",
    width: "36px",
    height: "36px",
    borderRadius: "8px",
    fontSize: "18px",
    cursor: "pointer",
  },
  mainMobile: {
    marginLeft: 0,
  },
  headerMobile: {
    padding: "16px 20px",
    flexWrap: "wrap",
    gap: "12px",
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  hamburgerBtn: {
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    border: "none",
    color: "#fff",
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    fontSize: "22px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pageTitleMobile: {
    fontSize: "20px",
  },
  addButtonMobile: {
    padding: "12px 16px",
    fontSize: "18px",
  },
  contentMobile: {
    padding: "16px",
  },
  cardHeaderMobile: {
    padding: "16px 20px",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "8px",
  },
  cardTitleMobile: {
    fontSize: "16px",
  },
  cardBodyMobile: {
    padding: "16px",
  },
  statsGridMobile: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  ordersCardsContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  orderCard: {
    background: "#fafbfc",
    border: "1px solid #e5e9f2",
    borderRadius: "12px",
    overflow: "hidden",
  },
  orderCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 16px",
    background: "#fff",
    borderBottom: "1px solid #e5e9f2",
  },
  orderCardId: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#1a1a2e",
  },
  statusBadge: {
    padding: "4px 12px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "600",
  },
  orderCardBody: {
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  orderCardRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  orderCardLabel: {
    fontSize: "13px",
    color: "#64748b",
    fontWeight: "500",
  },
  orderCardValue: {
    fontSize: "13px",
    color: "#1a1a2e",
    fontWeight: "500",
    textAlign: "right",
  },
  orderCardPrice: {
    fontSize: "15px",
    color: "#667eea",
    fontWeight: "700",
  },
  orderCardFooter: {
    padding: "12px 16px",
    background: "#fff",
    borderTop: "1px solid #e5e9f2",
  },
  statusSelect: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    fontSize: "14px",
    fontWeight: "500",
    color: "#1a1a2e",
    background: "#fff",
    cursor: "pointer",
    outline: "none",
  },
  emptyState: {
    textAlign: "center",
    padding: "40px 20px",
    color: "#8492a6",
    fontSize: "14px",
  },
  pagination: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "12px",
    marginTop: "8px",
    padding: "16px",
  },
  paginationBtn: {
    width: "40px",
    height: "40px",
    borderRadius: "10px",
    border: "1px solid #e5e9f2",
    background: "#fff",
    color: "#667eea",
    fontSize: "18px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.2s ease",
  },
  paginationBtnDisabled: {
    opacity: 0.4,
    cursor: "not-allowed",
  },
  paginationInfo: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#1a1a2e",
    minWidth: "60px",
    textAlign: "center",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  tableHeaderRow: {
    background: "#fafbfc",
    borderBottom: "2px solid #e5e9f2",
  },
  tableHeader: {
    padding: "14px 16px",
    textAlign: "left",
    fontSize: "13px",
    fontWeight: "600",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  tableRow: {
    borderBottom: "1px solid #e5e9f2",
    transition: "background 0.2s ease",
  },
  tableCell: {
    padding: "14px 16px",
    fontSize: "14px",
    color: "#1a1a2e",
  },
  helpText: {
    fontSize: "12px",
    color: "#8492a6",
    marginTop: "4px",
  },
  imagePreviewContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  imagePreview: {
    width: "200px",
    height: "200px",
    objectFit: "cover",
    borderRadius: "12px",
    border: "2px solid #e5e9f2",
  },
  cancelBtn: {
    padding: "14px 24px",
    background: "#f0f4f8",
    color: "#64748b",
    border: "1px solid #e2e8f0",
    borderRadius: "12px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  categoriesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: "16px",
  },
  categoryCard: {
    background: "#fafbfc",
    border: "1px solid #e5e9f2",
    borderRadius: "12px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  categoryCardContent: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  categoryImage: {
    width: "80px",
    height: "80px",
    objectFit: "cover",
    borderRadius: "10px",
    border: "1px solid #e5e9f2",
  },
  categoryTableImage: {
    width: "60px",
    height: "60px",
    objectFit: "cover",
    borderRadius: "8px",
    border: "1px solid #e5e9f2",
  },
  categoryInfo: {
    flex: 1,
  },
  categoryName: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#1a1a2e",
  },
  categoryActions: {
    display: "flex",
    gap: "8px",
  },
  editBtn: {
    flex: 1,
    padding: "10px 16px",
    background: "#fff",
    color: "#667eea",
    border: "1px solid #667eea",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  deleteBtn: {
    flex: 1,
    padding: "10px 16px",
    background: "#fff",
    color: "#dc3545",
    border: "1px solid #dc3545",
    borderRadius: "8px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
};
